export {default as LoadingPage } from './LoadingPage/LoadingPage'
export {default as Home } from './1-Home/Home'
export {default as Login } from './Login/Login'
export {default as SignUp } from './SignUp/SignUp'
export {default as Forget } from './Forget/Forget'
export {default as Phone } from './phone/phone'